# Generated by Django 4.0 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='boolshit', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default='hei'),
            preserve_default=False,
        ),
    ]
