# Generated by Django 4.0 on 2023-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_rename_text_post_text1_post_comments_post_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(default='hi i like yor post', max_length=30),
        ),
    ]
