# Generated by Django 4.0 on 2023-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_alter_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
    ]
